### PR TITLE
types: arena collect and control

### PR DESCRIPTION
**Pull request by HoPGoldy**
- [x] Add the type declaration about arena **collect and control**.
- [x] Add `RESOURCE_SCORE` to `ResourceConstant`.
- [x] Add `ScoreCollector` to param `target` in `Creep.transfer` method.

### CODE REVIEW

**Comment by ngbrown** [comment]
I think you need to add to `arena/prototypes/index.d.ts`:

```ts
/// <reference path="score-collector.d.ts" />
```

**Comment by thmsndk** [comment]
We are slowly moving over to https://github.com/screepers/typed-screeps-arena for the types. With this repo being purely a starter pack.

I will test this PR hopefully tonight, but would very much appreciate if you could also make a PR to the `develop` branch on the `typed-screeps-arena` repo

**Comment by HoPGoldy** [comment]
> I think you need to add to `arena/prototypes/index.d.ts`:
> 
> ```ts
> /// <reference path="score-collector.d.ts" />
> ```

I saw similar code at https://github.com/screepers/typed-screeps-arena, but I have question about it. It seems that I can also access the module before adding this reference. How can this help?

**Comment by HoPGoldy** [comment]
> We are slowly moving over to https://github.com/screepers/typed-screeps-arena for the types. With this repo being purely a starter pack.
> 
> I will test this PR hopefully tonight, but would very much appreciate if you could also make a PR to the `develop` branch on the `typed-screeps-arena` repo

I saw the similar code has already been submitted in [typed-screeps-arena](https://github.com/screepers/typed-screeps-arena) develop, it seems that I don’t need to submit another PR. ;)

**Pull request merged**
