### PR TITLE
Fix eslint error and warnings

### LINKED ISSUE #26: Eslint reports an error and warnings
```
$ npm run lint 

> screeps-arena-typescript-starter@3.0.0 lint
> eslint "src/**/*.ts"


/home/somq14/workspace/screeps-arena-typescript-starter/src/arena_capture_the_flag/main.ts
  32:10  warning  'BodyPart' is defined but never used  @typescript-eslint/no-unused-vars

/home/somq14/workspace/screeps-arena-typescript-starter/src/utils/ErrorMapper.ts
   8:9   warning  Unexpected dangling '_' in '_consumer'       no-underscore-dangle
   9:7   warning  Unexpected dangling '_' in '_consumer'       no-underscore-dangle
  12:12  warning  Unexpected dangling '_' in '_consumer'       no-underscore-dangle
  82:11  error    Expected space or tab after '//' in comment  spaced-comment

✖ 5 problems (1 error, 4 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.
```

### PR DESCRIPTION
**Pull request by somq14**
Fixes #26

### CODE REVIEW

**Comment by somq14** [comment]
Eslint reports following error.
I will fix them.

```
$ npm run lint

> screeps-arena-typescript-starter@3.0.0 lint
> eslint "src/**/*.ts"

Error: Error while loading rule '@typescript-eslint/no-loss-of-precision': @typescript-eslint/no-loss-of-precision requires at least ESLint v7.1.0
Occurred while linting /home/somq14/workspace/screeps-arena-typescript-starter/src/arena_2/main.ts
    at create (/home/somq14/workspace/screeps-arena-typescript-starter/node_modules/@typescript-eslint/eslint-plugin/dist/rules/no-loss-of-precision.js:46:19)
    at Object.create (/home/somq14/workspace/screeps-arena-typescript-starter/node_modules/@typescript-eslint/utils/dist/eslint-utils/RuleCreator.js:42:20)
    at createRuleListeners (/home/somq14/workspace/screeps-arena-typescript-starter/node_modules/eslint/lib/linter/linter.js:746:21)
    at /home/somq14/workspace/screeps-arena-typescript-starter/node_modules/eslint/lib/linter/linter.js:916:31
    at Array.forEach (<anonymous>)
    at runRules (/home/somq14/workspace/screeps-arena-typescript-starter/node_modules/eslint/lib/linter/linter.js:861:34)
    at Linter._verifyWithoutProcessors (/home/somq14/workspace/screeps-arena-typescript-starter/node_modules/eslint/lib/linter/linter.js:1157:31)
    at Linter._verifyWithConfigArray (/home/somq14/workspace/screeps-arena-typescript-starter/node_modules/eslint/lib/linter/linter.js:1255:21)
    at Linter.verify (/home/somq14/workspace/screeps-arena-typescript-starter/node_modules/eslint/lib/linter/linter.js:1210:25)
    at Linter.verifyAndFix (/home/somq14/workspace/screeps-arena-typescript-starter/node_modules/eslint/lib/linter/linter.js:1400:29)
```

**Comment by somq14** [comment]
I upgraded eslint and fixed eslint errors.

```
$ npm run lint

> screeps-arena-typescript-starter@3.0.0 lint
> eslint "src/**/*.ts"
```

**Comment by thmsndk** [comment]
Thanks for the PR, I'm not sure we want to remove the underscore dangle rule though. Let me think about it some more, and lets hear what others have to say.

The rest of the PR seems fine :)

**Comment by somq14** [comment]
Thank you for your comment.

In my opinion, we should leave it to users whether to enable the rule or not because we don't know which style users prefer.
Some javascript style guide uses dangling underscore, others do not.

I want to hear others too.

**Comment by glitchassassin** [comment]
The dangling underscore rule is because modern JS (and Typescript) now supports actual private members:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields#syntax

So representing private properties with an underscore is now an antipattern, and I think a warning is appropriate.

**Comment by somq14** [comment]
Thank you. That makes sence.
But I feel that it is a little too strict.
I want to discuss about eslint rules in another issue.

`ErrorMapper.ts` was deleted on develop branch, so there is no dangling underscore now.
I fixed all eslint problems without disabling `no-underscore-dangle` rule.

**Pull request merged**
