### PR TITLE
Enable editor.formatOnSave option

### LINKED ISSUE #32: Enable `editor.formatOnSave` option in VSCode workspace setting
I would like to enable "editor.formatOnSave" option.
https://github.com/screepers/screeps-arena-typescript-starter/blob/730cf512c50cee27175b799fc284d6ff698815ba/.vscode/settings.json#L8-L10

I do not know why [this commit](https://github.com/screepers/screeps-typescript-starter/commit/57990c4215b79cc95bdf17d34ba57648b375013b) disabled it.
I think it is useful.

### PR DESCRIPTION
**Pull request by somq14**
closes #32

### CODE REVIEW

**Comment by thmsndk** [comment]
Any particular reason for introducing the editorconfig extension, what does it exactly do that vscode does not do by default?

**Comment by somq14** [comment]
As far as I know, editorconfig extension only overrides settings.json based on .editorconfig file. So we can do same things which editorconfig do by manually configuring settings.json. I think that .editorconfig is better than settings.json because editorconfig is available on various editors other than vscode, some prettier's options respect settings in .editorconfig file. 

Actually, I added it without thinking deeply. I guessed that this starter was in favor of using editorconfig extension because it had `.editorconfig` file. So I decided to add editorconfig extension. 
Please let me know what you think about this.

**Comment by thmsndk** [comment]
I think I would prefer the starter kit working without the editor Config extension, I don't mind it being there to support other editors, but we can't be sure the people using the starter pack installs it 🤔

**Comment by somq14** [comment]
Right. I fixed the PR.
Could you review it again please?

**Pull request merged**
